#version: "3.8"
services:
  base:
    build:
      context: ./base 
      dockerfile: Dockerfile
    image: jaybhu05/open5gs-base:latest
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    volumes:
      - mongo_data:/data/db
    networks:
      - core-net
    ports:
      - "27018:27018"

  nrf:
    build:
      context: ./nrf
      dockerfile: Dockerfile
    image: jay.bhu05/open5gs-nrf:latest
    depends_on:
      - base
      - mongodb
    networks:
      - core-net
    environment:
      - LD_LIBRARY_PATH=/open5gs/lib:/open5gs/lib/x86_64-linux-gnu

  udm:
    build:
      context: ./udm
      dockerfile: Dockerfile
    image: jay.bhu05/open5gs-udm:latest
    depends_on:
      - mongodb
      - nrf
    networks:
      - core-net
    environment:
      - LD_LIBRARY_PATH=/open5gs/lib:/open5gs/lib/x86_64-linux-gnu
  
  ausf:
    build:
      context: ./ausf
      dockerfile: Dockerfile
    image: jay.bhu05/open5gs-ausf:latest
    depends_on:
      - mongodb
      - nrf
      - udm
    networks:
      - core-net

  pcf:
    build:
      context: ./pcf
      dockerfile: Dockerfile
    image: jay.bhu05/open5gs-pcf:latest
    depends_on:
      - mongodb
      - nrf
      - udm
    networks:
      - core-net

  amf:
    build:
      context: ./amf
      dockerfile: Dockerfile
    image: jaybhu05/open5gs-amf:latest
    depends_on:
      - mongodb
      - nrf
      - udm
    networks:
      - core-net

  smf:
    build:
      context: ./smf
      dockerfile: Dockerfile
    image: jaybhu05/open5gs-smf:latest
    depends_on:
      - mongodb
      - nrf
      - amf
      - udm
    networks:
      - core-net

  upf:
    build:
      context: ./upf
      dockerfile: Dockerfile
    image: jaybhu05/open5gs-upf:latest
    privileged: true
    depends_on:
      - smf
      - nrf
      - mongodb
    devices:
      - /dev/net/tun
    networks:
      - core-net


volumes:
  mongo_data:

networks:
  core-net:
    driver: bridge
