amf:
  amf_name: amf1.open5gs.amf.5gc.mnc01.mcc001.3gppnetwork.org
  sbi:
    server:
      - address: 127.0.0.21
        port: 7777
    client:
      nrf:
        - uri: http://127.0.0.10:7777  # <-- THIS IS CRITICAL
  ngap:
    server:
      - address: 127.0.0.21    # or the container’s IP / interface
        port: 38412         # 
  guami:
    - plmn_id:
        mcc: 001
        mnc: 01
      amf_id:
        region: 1
        set: 1
  tai:
    - plmn_id:
        mcc: 001
        mnc: 01
      tac: 1

  plmn_support:
    - plmn_id:
        mcc: 001
        mnc: 01
      s_nssai:
        - sst: 1

  security:
    integrity_order: [ NIA2, NIA1, NIA0 ]
    ciphering_order: [ NEA0, NEA1, NEA2 ]

  time:
    t3512:
      value: 540
