name: Build & Deploy Open5GS via Matrix Strategy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_images:
    name: Build & Push ${{ matrix.service }}
    runs-on: ubuntu-latest
    
    # Define the services to be built and pushed using a matrix
    strategy:
      fail-fast: false # Allows other services to continue building if one fails
      matrix:
        service: [base, nrf, udm, ausf, pcf, amf, smf, upf]
        repository: [jaybhu05] # Centralize the repository name

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (for multi-arch if needed)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      # Build and push the image for the current matrix service
      - name: Build & push ${{ matrix.service }} image
        uses: docker/build-push-action@v5
        with:
          # Context is the directory name, pulled from the matrix
          context: ./${{ matrix.service }}
          # Dockerfile is assumed to be 'Dockerfile' inside the context directory
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          # Tags are defined using the matrix service name
          tags: ${{ matrix.repository }}/open5gs-${{ matrix.service }}:latest

  deploy:
    name: Deploy to Server
    needs: build_images # This job waits until ALL images in build_images are successful
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository (for deployment files)
        uses: actions/checkout@v4

      - name: Package Open5GS files
        # Assuming 'open5gs-docker/' contains the necessary deployment files (like docker-compose.yml)
        run: |
          zip -r open5gs-package.zip open5gs-docker/

      - name: Deploy to server via SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Setup SSH key and permissions
          mkdir -p ~/.ssh
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # SCP and SSH commands
          scp -o StrictHostKeyChecking=no open5gs-package.zip project@10.0.2.15:/home/project/
          ssh -o StrictHostKeyChecking=no project@10.0.2.15 '
            echo "Deployment started on server..."
            cd /home/project
            unzip -o open5gs-package.zip
            echo "Pulling latest images (which were just pushed)..."
            docker-compose pull
            echo "Bringing up services..."
            docker-compose up -d
          '
          echo "Deployment command sent successfully."
